### ISSUE TITLE
Wordpress Plugin

### ISSUE THREAD

**Issue by convictedvapour** [JakeSidSmith/e-liquid-calculator#2]
Can I convert this into a WordPress plugin and if so what would be the starting point please? Many thanks in advance.

**Comment by convictedvapour** [comment]
This is as far as  I have got. I have a basic folder housing all the original files downloaded and the folder is entitled wp-eliquid. I have created wp-eliquid.php to house the following plugin file to make a basic plugin I am stuck from this point on. What I need is for it to display the content as on index.html (the calculator) on a wordpress page

I have also got a shortcode included so I can place `[eliquid]` in a page and it should successfully place the calculator on the page. The issue is how do I get the code into a plugin for WordPress please?

`<?php
/**
 * Plugin Name: WP Eliquid
 * Plugin URI: http://jailjuice.com/
 * Description: This plugin Calculates the e-liquid that you can make from base components.
 * Version: 1.0.0
 * Author: Plugin by Convicted Vapour original content author JakeSidSmith
 * Author URI: http://jailjuice.com/
 * License: GPL2
 */
 //[eliquid]
 add_shortcode('eliquid', 'get_eliquid');
 
 function get_eliquid($atts) {
	 //HTML TEXT STARTS HERE	

	 //HTML TEXT ENDS HERE
	;
}`

**Comment by convictedvapour** [comment]
Ignore this issue no longer required. Thanks.

**Comment by JakeSidSmith** [comment]
Sorry, never saw the issues you opened for some reason. Happy for you to take whatever you need and use it for anything you like. :)
